const model = {
    countries: [
        {
            name: "Afghanistan",
            continent: "Asia",
            capital: "Kabul",
            population: 38928346,
            area: 652230,
        },
        {
            name: "Albania",
            continent: "Europe",
            capital: "Tirana",
            population: 2877797,
            area: 28748,
        },
        {
            name: "Algeria",
            continent: "Africa",
            capital: "Algiers",
            population: 43851044,
            area: 2381741,
        },
        {
            name: "Andorra",
            continent: "Europe",
            capital: "Andorra la Vella",
            population: 77265,
            area: 468,
        },
        {
            name: "Angola",
            continent: "Africa",
            capital: "Luanda",
            population: 32866272,
            area: 1246700,
        },
        {
            name: "Antigua and Barbuda",
            continent: "North America",
            capital: "St. John's",
            population: 97928,
            area: 442,
        },
        {
            name: "Argentina",
            continent: "South America",
            capital: "Buenos Aires",
            population: 45195777,
            area: 2780400,
        },
        {
            name: "Armenia",
            continent: "Asia",
            capital: "Yerevan",
            population: 2963243,
            area: 29743,
        },
        {
            name: "Australia",
            continent: "Australia",
            capital: "Canberra",
            population: 25499884,
            area: 7692024,
        },
        {
            name: "Austria",
            continent: "Europe",
            capital: "Vienna",
            population: 9006398,
            area: 83871,
        },
        {
            name: "Azerbaijan",
            continent: "Asia",
            capital: "Baku",
            population: 10139177,
            area: 86600,
        },
        {
            name: "Bahamas",
            continent: "North America",
            capital: "Nassau",
            population: 393244,
            area: 13940,
        },
        {
            name: "Bahrain",
            continent: "Asia",
            capital: "Manama",
            population: 1701575,
            area: 760,
        },
        {
            name: "Bangladesh",
            continent: "Asia",
            capital: "Dhaka",
            population: 164689383,
            area: 147570,
        },
        {
            name: "Barbados",
            continent: "North America",
            capital: "Bridgetown",
            population: 287375,
            area: 431,
        },
        {
            name: "Belarus",
            continent: "Europe",
            capital: "Minsk",
            population: 9449323,
            area: 207600,
        },
        {
            name: "Belgium",
            continent: "Europe",
            capital: "Brussels",
            population: 11589623,
            area: 30528,
        },
        {
            name: "Belize",
            continent: "North America",
            capital: "Belmopan",
            population: 397628,
            area: 22966,
        },
        {
            name: "Benin",
            continent: "Africa",
            capital: "Porto-Novo",
            population: 12123198,
            area: 112622,
        },
        {
            name: "Bhutan",
            continent: "Asia",
            capital: "Thimphu",
            population: 771608,
            area: 38394,
        },
        {
            name: "Bolivia",
            continent: "South America",
            capital: "La Paz",
            population: 11673021,
            area: 1098581,
        },
        {
            name: "Bosnia and Herzegovina",
            continent: "Europe",
            capital: "Sarajevo",
            population: 3280815,
            area: 51197,
        },
        {
            name: "Botswana",
            continent: "Africa",
            capital: "Gaborone",
            population: 2351627,
            area: 581730,
        },
        {
            name: "Brazil",
            continent: "South America",
            capital: "Brasília",
            population: 212559417,
            area: 8515767,
        },
        {
            name: "Brunei",
            continent: "Asia",
            capital: "Bandar Seri Begawan",
            population: 437479,
            area: 5765,
        },
        {
            name: "Bulgaria",
            continent: "Europe",
            capital: "Sofia",
            population: 6948445,
            area: 110879,
        },
        {
            name: "Burkina Faso",
            continent: "Africa",
            capital: "Ouagadougou",
            population: 20903278,
            area: 274200,
        },
        {
            name: "Burundi",
            continent: "Africa",
            capital: "Bujumbura",
            population: 11890784,
            area: 27834,
        },
        {
            name: "Cabo Verde",
            continent: "Africa",
            capital: "Praia",
            population: 555987,
            area: 4033,
        },
        {
            name: "Cambodia",
            continent: "Asia",
            capital: "Phnom Penh",
            population: 16718971,
            area: 181035,
        },
        {
            name: "Cameroon",
            continent: "Africa",
            capital: "Yaoundé",
            population: 26545864,
            area: 475442,
        },
        {
            name: "Canada",
            continent: "North America",
            capital: "Ottawa",
            population: 37742154,
            area: 9984670,
        },
        {
            name: "Central African Republic",
            continent: "Africa",
            capital: "Bangui",
            population: 4829767,
            area: 622984,
        },
        {
            name: "Chad",
            continent: "Africa",
            capital: "N'Djamena",
            population: 16425859,
            area: 1284000,
        },
        {
            name: "Chile",
            continent: "South America",
            capital: "Santiago",
            population: 19116201,
            area: 756102,
        },
        {
            name: "China",
            continent: "Asia",
            capital: "Beijing",
            population: 1444216107,
            area: 9596961,
        },
        {
            name: "Colombia",
            continent: "South America",
            capital: "Bogotá",
            population: 50882891,
            area: 1141748,
        },
        {
            name: "Comoros",
            continent: "Africa",
            capital: "Moroni",
            population: 869601,
            area: 1862,
        },
        {
            name: "Congo (Congo-Brazzaville)",
            continent: "Africa",
            capital: "Brazzaville",
            population: 5518087,
            area: 342000,
        },
        {
            name: "Costa Rica",
            continent: "North America",
            capital: "San José",
            population: 5094118,
            area: 51100,
        },
        {
            name: "Croatia",
            continent: "Europe",
            capital: "Zagreb",
            population: 4105267,
            area: 56594,
        },
        {
            name: "Cuba",
            continent: "North America",
            capital: "Havana",
            population: 11326616,
            area: 110861,
        },
        {
            name: "Cyprus",
            continent: "Asia",
            capital: "Nicosia",
            population: 1207359,
            area: 5896,
        },
        {
            name: "Czechia (Czech Republic)",
            continent: "Europe",
            capital: "Prague",
            population: 10708981,
            area: 78865,
        },
        {
            name: "Democratic Republic of the Congo (Congo-Kinshasa)",
            continent: "Africa",
            capital: "Kinshasa",
            population: 85026000,
            area: 2344858,
        },
        {
            name: "Denmark",
            continent: "Europe",
            capital: "Copenhagen",
            population: 5792202,
            area: 43094,
        },
        {
            name: "Djibouti",
            continent: "Africa",
            capital: "Djibouti",
            population: 988000,
            area: 23000,
        },
        {
            name: "Dominica",
            continent: "North America",
            capital: "Roseau",
            population: 71986,
            area: 751,
        },
        {
            name: "Dominican Republic",
            continent: "North America",
            capital: "Santo Domingo",
            population: 10847910,
            area: 48671,
        },
        {
            name: "East Timor (Timor-Leste)",
            continent: "Asia",
            capital: "Dili",
            population: 1318445,
            area: 14874,
        },
        {
            name: "Ecuador",
            continent: "South America",
            capital: "Quito",
            population: 17643054,
            area: 276841,
        },
        {
            name: "Egypt",
            continent: "Africa",
            capital: "Cairo",
            population: 102334404,
            area: 1002450,
        },
        {
            name: "El Salvador",
            continent: "North America",
            capital: "San Salvador",
            population: 6486205,
            area: 21041,
        },
        {
            name: "Equatorial Guinea",
            continent: "Africa",
            capital: "Malabo",
            population: 1402985,
            area: 28051,
        },
        {
            name: "Eritrea",
            continent: "Africa",
            capital: "Asmara",
            population: 3546421,
            area: 117600,
        },
        {
            name: "Estonia",
            continent: "Europe",
            capital: "Tallinn",
            population: 1326535,
            area: 45227,
        },
        {
            name: "Eswatini (fmr. "Swaziland")",
            continent: "Africa",
            capital: "Mbabane",
            population: 1160164,
            area: 17364,
        },
        {
            name: "Ethiopia",
            continent: "Africa",
            capital: "Addis Ababa",
            population: 114963588,
            area: 1104300,
        },
        {
            name: "Fiji",
            continent: "Oceania",
            capital: "Suva",
            population: 896445,
            area: 18274,
        },
        {
            name: "Finland",
            continent: "Europe",
            capital: "Helsinki",
            population: 5540720,
            area: 338424,
        },
        {
            name: "France",
            continent: "Europe",
            capital: "Paris",
            population: 65273511,
            area: 551695,
        },
        {
            name: "Gabon",
            continent: "Africa",
            capital: "Libreville",
            population: 2225734,
            area: 267667,
        },
        {
            name: "Gambia",
            continent: "Africa",
            capital: "Banjul",
            population: 2416668,
            area: 11295,
        },
        {
            name: "Georgia",
            continent: "Asia",
            capital: "Tbilisi",
            population: 3989167,
            area: 69700,
        },
        {
            name: "Germany",
            continent: "Europe",
            capital: "Berlin",
            population: 83783942,
            area: 357022,
        },
        {
            name: "Ghana",
            continent: "Africa",
            capital: "Accra",
            population: 31072940,
            area: 238533,
        },
        {
            name: "Greece",
            continent: "Europe",
            capital: "Athens",
            population: 10423054,
            area: 131957,
        },
        {
            name: "Grenada",
            continent: "North America",
            capital: "St. George's",
            population: 112523,
            area: 344,
        },
        {
            name: "Guatemala",
            continent: "North America",
            capital: "Guatemala City",
            population: 17915568,
            area: 108889,
        },
        {
            name: "Guinea",
            continent: "Africa",
            capital: "Conakry",
            population: 13132795,
            area: 245857,
        },
        {
            name: "Guinea-Bissau",
            continent: "Africa",
            capital: "Bissau",
            population: 1967998,
            area: 36125,
        },
        {
            name: "Guyana",
            continent: "South America",
            capital: "Georgetown",
            population: 786552,
            area: 214969,
        },
        {
            name: "Haiti",
            continent: "North America",
            capital: "Port-au-Prince",
            population: 11402533,
            area: 27750,
        },
        {
            name: "Holy See",
            continent: "Europe",
            capital: "Vatican City",
            population: 801,
            area: 0.44,
        },
        {
            name: "Honduras",
            continent: "North America",
            capital: "Tegucigalpa",
            population: 9904607,
            area: 112492,
        },
        {
            name: "Hungary",
            continent: "Europe",
            capital: "Budapest",
            population: 9660351,
            area: 93030,
        },
        {
            name: "Iceland",
            continent: "Europe",
            capital: "Reykjavik",
            population: 341243,
            area: 103000,
        },
        {
            name: "India",
            continent: "Asia",
            capital: "New Delhi",
            population: 1380004385,
            area: 3287263,
        },
        {
            name: "Indonesia",
            continent: "Asia",
            capital: "Jakarta",
            population: 273523615,
            area: 1904569,
        },
        {
            name: "Iran",
            continent: "Asia",
            capital: "Tehran",
            population: 83992949,
            area: 1648195,
        },
        {
            name: "Iraq",
            continent: "Asia",
            capital: "Baghdad",
            population: 40222493,
            area: 438317,
        },
        {
            name: "Ireland",
            continent: "Europe",
            capital: "Dublin",
            population: 4937786,
            area: 70273,
        },
        {
            name: "Israel",
            continent: "Asia",
            capital: "Jerusalem",
            population: 8655535,
            area: 20770,
        },
        {
            name: "Italy",
            continent: "Europe",
            capital: "Rome",
            population: 60461826,
            area: 301340,
        },
        {
            name: "Jamaica",
            continent: "North America",
            capital: "Kingston",
            population: 2961161,
            area: 10991,
        },
        {
            name: "Japan",
            continent: "Asia",
            capital: "Tokyo",
            population: 126476461,
            area: 377975,
        },
        {
            name: "Jordan",
            continent: "Asia",
            capital: "Amman",
            population: 10203134,
            area: 89342,
        },
        {
            name: "Kazakhstan",
            continent: "Asia",
            capital: "Nur-Sultan",
            population: 18776707,
            area: 2724900,
        },
        {
            name: "Kenya",
            continent: "Africa",
            capital: "Nairobi",
            population: 53771296,
            area: 580367,
        },
        {
            name: "Kiribati",
            continent: "Oceania",
            capital: "Tarawa",
            population: 119449,
            area: 811,
        },
        {
            name: "Kuwait",
            continent: "Asia",
            capital: "Kuwait City",
            population: 4270571,
            area: 17818,
        },
        {
            name: "Kyrgyzstan",
            continent: "Asia",
            capital: "Bishkek",
            population: 6524195,
            area: 199951,
        },
        {
            name: "Laos",
            continent: "Asia",
            capital: "Vientiane",
            population: 7275560,
            area: 236800,
        },
        {
            name: "Latvia",
            continent: "Europe",
            capital: "Riga",
            population: 1886198,
            area: 64559,
        },
        {
            name: "Lebanon",
            continent: "Asia",
            capital: "Beirut",
            population: 6825442,
            area: 10452,
        },
        {
            name: "Lesotho",
            continent: "Africa",
            capital: "Maseru",
            population: 2142249,
            area: 30355,
        },
        {
            name: "Liberia",
            continent: "Africa",
            capital: "Monrovia",
            population: 5057681,
            area: 111369,
        },
        {
            name: "Libya",
            continent: "Africa",
            capital: "Tripoli",
            population: 6871287,
            area: 1759540,
        },
        {
            name: "Liechtenstein",
            continent: "Europe",
            capital: "Vaduz",
            population: 38128,
            area: 160,
        },
        {
            name: "Lithuania",
            continent: "Europe",
            capital: "Vilnius",
            population: 2722289,
            area: 65300,
        },
        {
            name: "Luxembourg",
            continent: "Europe",
            capital: "Luxembourg City",
            population: 625978,
            area: 2586,
        },
        {
            name: "Madagascar",
            continent: "Africa",
            capital: "Antananarivo",
            population: 27691019,
            area: 587041,
        },
        {
            name: "Malawi",
            continent: "Africa",
            capital: "Lilongwe",
            population: 19129952,
            area: 118484,
        },
        {
            name: "Malaysia",
            continent: "Asia",
            capital: "Kuala Lumpur",
            population: 32365999,
            area: 330803,
        },
        {
            name: "Maldives",
            continent: "Asia",
            capital: "Malé",
            population: 521167,
            area: 298,
        },
        {
            name: "Mali",
            continent: "Africa",
            capital: "Bamako",
            population: 20250833,
            area: 1240192,
        },
        {
            name: "Malta",
            continent: "Europe",
            capital: "Valletta",
            population: 441543,
            area: 316,
        },
        {
            name: "Marshall Islands",
            continent: "Oceania",
            capital: "Majuro",
            population: 59190,
            area: 181,
        },
        {
            name: "Mauritania",
            continent: "Africa",
            capital: "Nouakchott",
            population: 4649658,
            area: 1030700,
        },
        {
            name: "Mauritius",
            continent: "Africa",
            capital: "Port Louis",
            population: 1271768,
            area: 2040,
        },
        {
            name: "Mexico",
            continent: "North America",
            capital: "Mexico City",
            population: 128932753,
            area: 1964375,
        },
        {
            name: "Micronesia",
            continent: "Oceania",
            capital: "Palikir",
            population: 115023,
            area: 702,
        },
        {
            name: "Moldova",
            continent: "Europe",
            capital: "Chisinau",
            population: 4033963,
            area: 33846,
        },
        {
            name: "Monaco",
            continent: "Europe",
            capital: "Monaco",
            population: 39242,
            area: 2,
        },
        {
            name: "Mongolia",
            continent: "Asia",
            capital: "Ulaanbaatar",
            population: 3278290,
            area: 1564116,
        },
        {
            name: "Montenegro",
            continent: "Europe",
            capital: "Podgorica",
            population: 628066,
            area: 13812,
        },
        {
            name: "Morocco",
            continent: "Africa",
            capital: "Rabat",
            population: 36910560,
            area: 446550,
        },
        {
            name: "Mozambique",
            continent: "Africa",
            capital: "Maputo",
            population: 31255435,
            area: 801590,
        },
        {
            name: "Myanmar (Burma)",
            continent: "Asia",
            capital: "Naypyidaw",
            population: 54409800,
            area: 676578,
        },
        {
            name: "Namibia",
            continent: "Africa",
            capital: "Windhoek",
            population: 2540905,
            area: 824292,
        },
        {
            name: "Nauru",
            continent: "Oceania",
            capital: "Yaren",
            population: 10824,
            area: 21,
        },
        {
            name: "Nepal",
            continent: "Asia",
            capital: "Kathmandu",
            population: 29136808,
            area: 147516,
        },
        {
            name: "Netherlands",
            continent: "Europe",
            capital: "Amsterdam",
            population: 17134872,
            area: 41543,
        },
        {
            name: "New Zealand",
            continent: "Oceania",
            capital: "Wellington",
            population: 4822233,
            area: 270467,
        },
        {
            name: "Nicaragua",
            continent: "North America",
            capital: "Managua",
            population: 6624554,
            area: 130375,
        },
        {
            name: "Niger",
            continent: "Africa",
            capital: "Niamey",
            population: 24206636,
            area: 1186408,
        },
        {
            name: "Nigeria",
            continent: "Africa",
            capital: "Abuja",
            population: 206139587,
            area: 923768,
        },
        {
            name: "North Korea (DPRK)",
            continent: "Asia",
            capital: "Pyongyang",
            population: 25778816,
            area: 120538,
        },
        {
            name: "North Macedonia",
            continent: "Europe",
            capital: "Skopje",
            population: 2083374,
            area: 25713,
        },
        {
            name: "Norway",
            continent: "Europe",
            capital: "Oslo",
            population: 5421241,
            area: 323802,
        },
        {
            name: "Oman",
            continent: "Asia",
            capital: "Muscat",
            population: 5106626,
            area: 309500,
        },
        {
            name: "Pakistan",
            continent: "Asia",
            capital: "Islamabad",
            population: 220892340,
            area: 881913,
        },
        {
            name: "Palau",
            continent: "Oceania",
            capital: "Ngerulmud",
            population: 18094,
            area: 459,
        },
        {
            name: "Palestine State",
            continent: "Asia",
            capital: "East Jerusalem",
            population: 5101414,
            area: 6020,
        },
        {
            name: "Panama",
            continent: "North America",
            capital: "Panama City",
            population: 4314767,
            area: 75420,
        },
        {
            name: "Papua New Guinea",
            continent: "Oceania",
            capital: "Port Moresby",
            population: 8947024,
            area: 462840,
        },
        {
            name: "Paraguay",
            continent: "South America",
            capital: "Asunción",
            population: 7132530,
            area: 406752,
        },
        {
            name: "Peru",
            continent: "South America",
            capital: "Lima",
            population: 32971854,
            area: 1285216,
        },
        {
            name: "Philippines",
            continent: "Asia",
            capital: "Manila",
            population: 113993580,
            area: 342353,
        },
        {
            name: "Poland",
            continent: "Europe",
            capital: "Warsaw",
            population: 37846611,
            area: 312696,
        },
        {
            name: "Portugal",
            continent: "Europe",
            capital: "Lisbon",
            population: 10196709,
            area: 92090,
        },
        {
            name: "Qatar",
            continent: "Asia",
            capital: "Doha",
            population: 2881053,
            area: 11586,
        },
        {
            name: "Romania",
            continent: "Europe",
            capital: "Bucharest",
            population: 19237691,
            area: 238397,
        },
        {
            name: "Russia",
            continent: "Europe/Asia",
            capital: "Moscow",
            population: 145912025,
            area: 17125242,
        },
        {
            name: "Rwanda",
            continent: "Africa",
            capital: "Kigali",
            population: 12952218,
            area: 26338,
        },
        {
            name: "Saint Kitts and Nevis",
            continent: "North America",
            capital: "Basseterre",
            population: 53199,
            area: 261,
        },
        {
            name: "Saint Lucia",
            continent: "North America",
            capital: "Castries",
            population: 183627,
            area: 616,
        },
        {
            name: "Saint Vincent and the Grenadines",
            continent: "North America",
            capital: "Kingstown",
            population: 110940,
            area: 389,
        },
        {
            name: "Samoa",
            continent: "Oceania",
            capital: "Apia",
            population: 198414,
            area: 2831,
        },
        {
            name: "San Marino",
            continent: "Europe",
            capital: "San Marino",
            population: 33938,
            area: 61,
        },
        {
            name: "Sao Tome and Principe",
            continent: "Africa",
            capital: "São Tomé",
            population: 219159,
            area: 964,
        },
        {
            name: "Saudi Arabia",
            continent: "Asia",
            capital: "Riyadh",
            population: 34813871,
            area: 2149690,
        },
        {
            name: "Senegal",
            continent: "Africa",
            capital: "Dakar",
            population: 16743927,
            area: 196722,
        },
        {
            name: "Serbia",
            continent: "Europe",
            capital: "Belgrade",
            population: 8737371,
            area: 77474,
        },
        {
            name: "Seychelles",
            continent: "Africa",
            capital: "Victoria",
            population: 98347,
            area: 459,
        },
        {
            name: "Sierra Leone",
            continent: "Africa",
            capital: "Freetown",
            population: 7976983,
            area: 71740,
        },
        {
            name: "Singapore",
            continent: "Asia",
            capital: "Singapore",
            population: 5850342,
            area: 719,
        },
        {
            name: "Slovakia",
            continent: "Europe",
            capital: "Bratislava",
            population: 5460109,
            area: 49035,
        },
        {
            name: "Slovenia",
            continent: "Europe",
            capital: "Ljubljana",
            population: 2078938,
            area: 20273,
        },
        {
            name: "Solomon Islands",
            continent: "Oceania",
            capital: "Honiara",
            population: 686878,
            area: 28896,
        },
        {
            name: "Somalia",
            continent: "Africa",
            capital: "Mogadishu",
            population: 15893222,
            area: 637657,
        },
        {
            name: "South Africa",
            continent: "Africa",
            capital: "Pretoria, Bloemfontein, Cape Town",
            population: 59308690,
            area: 1221037,
        },
        {
            name: "South Korea (Republic of Korea)",
            continent: "Asia",
            capital: "Seoul",
            population: 51269185,
            area: 100210,
        },
        {
            name: "South Sudan",
            continent: "Africa",
            capital: "Juba",
            population: 11193729,
            area: 619745,
        },
        {
            name: "Spain",
            continent: "Europe",
            capital: "Madrid",
            population: 46754778,
            area: 505990,
        },
        {
            name: "Sri Lanka",
            continent: "Asia",
            capital: "Colombo",
            population: 21413249,
            area: 65610,
        },
        {
            name: "Sudan",
            continent: "Africa",
            capital: "Khartoum",
            population: 43849260,
            area: 1861484,
        },
        {
            name: "Suriname",
            continent: "South America",
            capital: "Paramaribo",
            population: 586632,
            area: 163821,
        },
        {
            name: "Sweden",
            continent: "Europe",
            capital: "Stockholm",
            population: 10099265,
            area: 450295,
        },
        {
            name: "Switzerland",
            continent: "Europe",
            capital: "Bern",
            population: 8654622,
            area: 41284,
        },
        {
            name: "Syria",
            continent: "Asia",
            capital: "Damascus",
            population: 17500657,
            area: 185180,
        },
        {
            name: "Tajikistan",
            continent: "Asia",
            capital: "Dushanbe",
            population: 9537645,
            area: 143100,
        },
        {
            name: "Tanzania",
            continent: "Africa",
            capital: "Dodoma",
            population: 59734218,
            area: 947303,
        },
        {
            name: "Thailand",
            continent: "Asia",
            capital: "Bangkok",
            population: 69799978,
            area: 513120,
        },
        {
            name: "Togo",
            continent: "Africa",
            capital: "Lome",
            population: 8278737,
            area: 56785,
        },
        {
            name: "Tonga",
            continent: "Oceania",
            capital: "Nuku'alofa",
            population: 105695,
            area: 747,
        },
        {
            name: "Trinidad and Tobago",
            continent: "North America",
            capital: "Port of Spain",
            population: 1394973,
            area: 5130,
        },
        {
            name: "Tunisia",
            continent: "Africa",
            capital: "Tunis",
            population: 11818619,
            area: 163610,
        },
        {
            name: "Turkey",
            continent: "Asia/Europe",
            capital: "Ankara",
            population: 84339067,
            area: 783562,
        },
        {
            name: "Turkmenistan",
            continent: "Asia",
            capital: "Ashgabat",
            population: 6031187,
            area: 488100,
        },
        {
            name: "Tuvalu",
            continent: "Oceania",
            capital: "Funafuti",
            population: 11704,
            area: 26,
        },
        {
            name: "Uganda",
            continent: "Africa",
            capital: "Kampala",
            population: 45741007,
            area: 241038,
        },
        {
            name: "Ukraine",
            continent: "Europe",
            capital: "Kyiv",
            population: 44385155,
            area: 603500,
        },
        {
            name: "United Arab Emirates",
            continent: "Asia",
            capital: "Abu Dhabi",
            population: 9890402,
            area: 83600,
        },
        {
            name: "United Kingdom",
            continent: "Europe",
            capital: "London",
            population: 67886011,
            area: 242495,
        },
        {
            name: "United States of America",
            continent: "North America",
            capital: "Washington, D.C.",
            population: 331002651,
            area: 9372610,
        },
        {
            name: "Uruguay",
            continent: "South America",
            capital: "Montevideo",
            population: 3473730,
            area: 181034,
        },
        {
            name: "Uzbekistan",
            continent: "Asia",
            capital: "Tashkent",
            population: 33469203,
            area: 448978,
        },
        {
            name: "Vanuatu",
            continent: "Oceania",
            capital: "Port Vila",
            population: 307145,
            area: 12189,
        },
        {
            name: "Venezuela",
            continent: "South America",
            capital: "Caracas",
            population: 28435943,
            area: 916445,
        },
        {
            name: "Vietnam",
            continent: "Asia",
            capital: "Hanoi",
            population: 97338579,
            area: 331212,
        },
        {
            name: "Yemen",
            continent: "Asia",
            capital: "Sanaa",
            population: 29825968,
            area: 527968,
        },
        {
            name: "Zambia",
            continent: "Africa",
            capital: "Lusaka",
            population: 18383955,
            area: 752612,
        },
        {
            name: "Zimbabwe",
            continent: "Africa",
            capital: "Harare",
            population: 14862927,
            area: 390757,
        },
    ]
};
